units:
  # Size of each key. cx and cy for choc, u and U for MX.
  kx: cx
  ky: cy
  # key spread and padding
  px: 1.04kx
  py: 1.04ky
  # From that, get the spacing between keys
  ksx: px-kx
  ksy: py-ky
  lpx: px + 1
  
  # Stagger for all of the different columns
  stagger1: py # ring column one key above the pinky column
  stagger2: 0.3py # middle column .3 key above the ring column
  stagger3: -0.6py # index
  stagger4: -0.2py # inner

  # Sizes of things
  mountinghole_radius: 3
  mountinghole_diameter: 2*mountinghole_radius

  # Other constants
  xiao_shift_x: -1.5
  xiao_shift_y: 1py+0.39

  tr_mh_sx: -0.5cx+mountinghole_radius
  tr_mh_sy: 0.5cy+mountinghole_radius
  bm_mh_sx: -0.5kx-ksx+mountinghole_radius
  bm_mh_sy: -0.5ky-mountinghole_radius

points:
  key:
    spread: 1px
    padding: 1py
  zones:
    matrix:
      columns:
        pinky:
          key:
            column_net: P3
        ring:
          key:
            stagger: stagger1
            column_net: P4
        middle:
          key:
            stagger: stagger2
            column_net: P5
        index:
          key:
            stagger: stagger3
            column_net: P6
        inner:
          key:
            stagger: stagger4
            column_net: P8
      rows:
        bottom:
          row_net: P0
        home:
          row_net: P1
        top:
          row_net: P2
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-1px, -py]
      columns:
        inner:
          key:
            column_net: P6
        home:
          key:
            column_net: P8
      rows:
        thumb:
          row_net: P9

outlines:
  board_noround:
    - what: rectangle
      where: true
      size: [lpx, py]
    - # Between board and thumbfan
      what: polygon
      points:
        - ref: matrix_pinky_bottom # Top left
          shift: [-0.5lpx, 1ky]
        - ref: matrix_pinky_bottom # Top right
          shift: [4kx, 1ky]
        - ref: matrix_pinky_bottom # Bottom right
          shift: [4kx, -0.5py]
        - ref: matrix_pinky_bottom # Bottom left
          shift: [-0.5lpx, -0.5py]
    - # MCU
      what: polygon
      points:
        - ref: matrix_pinky_top # Top left
          shift: [-12, 29.46]
        - ref: matrix_pinky_top # Top right
          shift: [9+lpx, 29.46]
        - ref: matrix_pinky_top # Top-middle right (for link with matrix)
          shift: [9+0.5lpx, -0.5py]
        - ref: matrix_pinky_top # Still
          shift: [0.5lpx, -0.5py]
        - ref: matrix_pinky_bottom # Bottom-middle right (for link with matrix)
          shift: [0.5lpx, -0.5py]
        - ref: matrix_pinky_bottom # Bottom left
          shift: [-12, -0.5py]
    - # Top right for slider and screw hole
      what: polygon
      points:
        - ref: matrix_index_top # Top left
          shift: [-0.5lpx, 0.5ky+mountinghole_diameter]
        - ref: matrix_index_top # Top right
          shift: [0.5lpx, 0.5ky+mountinghole_diameter]
        - ref: matrix_index_top # Bottom right
          shift: [0.5lpx, 0.5py]
        - ref: matrix_index_top # Bottom left
          shift: [-0.5lpx, 0.5py]


  board:
    - what: outline
      name: board_noround
      fillet: 1

  plate_base:
    - # Main board
      what: polygon
      points:
        - ref: matrix_pinky_top # Top left
          shift: [-0.5cx, 0.5ky]
        - ref: matrix_pinky_top
          shift: [0.5px, 0.5ky]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5ky]
        - ref: matrix_ring_top
          shift: [0.5px, 0.5ky]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5ky]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5ky]
        - ref: matrix_index_top
          shift: [-0.5px, 0.5ky]
        - ref: matrix_index_top
          shift: [0.5px, 0.5ky]
        - ref: matrix_inner_top
          shift: [-0.5px, 0.5ky]
        - ref: matrix_inner_top # Top right
          shift: [0.5cx, 0.5ky]
        - ref: matrix_inner_bottom
          shift: [0.5cx, -0.5py]
        - ref: thumbfan_home_thumb # Bottom right
          shift: [0.5cx, -0.5py]
        - ref: thumbfan_inner_thumb
          shift: [-0.5px, -0.5py]
        - ref: matrix_index_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_index_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_middle_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_middle_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_ring_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_ring_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_bottom 
          shift: [0.5px, -0.5py]
        - ref: matrix_pinky_bottom # Bottom left
          shift: [-0.5cx, -0.5py]
    - # Between the inner thumb key and the board
      what: polygon
      points:
        - ref: thumbfan_inner_thumb # Top left
          shift: [-0.5px, 2py]
        - ref: thumbfan_inner_thumb # Top right
          shift: [1px, 2py]
        - ref: thumbfan_inner_thumb # Bottom right
          shift: [1px, -0.5py]
        - ref: thumbfan_inner_thumb # Bottom left
          shift: [-0.5px, -0.5py]
    - # Top right mounting hole
      what: polygon
      points:
        - ref: matrix_index_top # Top left
          shift: [-px, tr_mh_sy+mountinghole_radius]
        - ref: matrix_index_top # Top of the hole footprint
          shift: [tr_mh_sx, tr_mh_sy+mountinghole_radius]
        - ref: matrix_index_top # Middle
          shift: [tr_mh_sx, tr_mh_sy]
        - ref: matrix_index_top # Right of the hole footprint
          shift: [tr_mh_sx+mountinghole_radius, tr_mh_sy]
        - ref: matrix_index_top # Bottom right
          shift: [tr_mh_sx+mountinghole_radius, 0]
        - ref: matrix_index_top # Bottom left
          shift: [-px, 0]
    - what: circle
      where:
        ref: matrix_index_top
        shift: [tr_mh_sx, tr_mh_sy]
      radius: mountinghole_radius
    - # Bottom middle mounting hole
      what: polygon
      points:
        - ref: matrix_middle_bottom # Top left
          shift: [-2px, 0]
        - ref: matrix_middle_bottom # Top right
          shift: [bm_mh_sx+mountinghole_radius, 0]
        - ref: matrix_middle_bottom # Right of the hole footprint
          shift: [bm_mh_sx+mountinghole_radius, bm_mh_sy]
        - ref: matrix_middle_bottom # Middle of the hole footprint
          shift: [bm_mh_sx, bm_mh_sy]
        - ref: matrix_middle_bottom # Bottom of the hole footprint
          shift: [bm_mh_sx, bm_mh_sy-mountinghole_radius]
        - ref: matrix_middle_bottom # Bottom left
          shift: [-2px, bm_mh_sy-mountinghole_radius]
    - what: circle
      where:
        ref: matrix_middle_bottom
        shift: [bm_mh_sx, bm_mh_sy]
      radius: mountinghole_radius

  plate:
    - what: outline
      name: plate_base
      fillet: 1
    - what: rectangle
      where: true
      size: 14
      operation: subtract

pcbs:
  main:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: pad_diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -0.3py]
      diode_via_1:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [2.8, -0.3py]
      diode_via_2:
        what: via
        where: true
        params:
          net: "{{row_net}}"
        adjust:
          shift: [-2.8, -0.3py]
      key_via_1:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [0, 3.67]
      key_via_2:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [0, 2.67]
      xiao:
        what: xiao
        params:
          orientation: up # Reset button on the bottom
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y + 2.5]
          rotate: 90
      xiao-reverse:
        what: xiao
        params:
          orientation: down
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y]
          rotate: 90
      battery_pad:
        what: battery_pad
        where:
          ref: matrix_middle_bottom
          shift: [5, -0.5ky-2]
          rotate: 0
        params:
          plus: BAT+
          minus: GND
      slider_f:
        what: slider
        where:
          ref: matrix_index_top
          shift: [4, 0.5ky+mountinghole_diameter-2]
          rotate: 0
        params:
          from: BAT+
          to: XIAO_BAT+
          side: F
      slider_b:
        what: slider
        where:
          ref: matrix_index_top
          shift: [4, 0.5ky+mountinghole_diameter-2]
          rotate: 0
        params:
          from: BAT+
          to: XIAO_BAT+
          side: B
      batt_pad:
        what: pad
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y + 2.5]
        params:
          net: XIAO_BAT+
          width: 1.5
          height: 1.5
      mountinghole_top_right:
        what: mountinghole
        where:
          ref: matrix_index_top
          shift: [tr_mh_sx, tr_mh_sy]
      mountinghole_bottom_middle:
        what: mountinghole
        where:
          ref: matrix_middle_bottom
          shift: [bm_mh_sx, bm_mh_sy]
  plate:
    outlines:
      plate:
        outline: plate
    footprints:
      mountinghole_top_right:
        what: mountinghole
        where:
          ref: matrix_index_top
          shift: [tr_mh_sx, tr_mh_sy]
      mountinghole_bottom_middle:
        what: mountinghole
        where:
          ref: matrix_middle_bottom
          shift: [bm_mh_sx, bm_mh_sy]
