units:
  # Size of each key. cx and cy for choc, u and U for MX.
  kx: cx
  ky: cy
  # key spread and padding
  px: 1.04kx
  py: 1.04ky
  # From that, get the spacing between keys
  ksx: px-kx
  ksy: py-ky
  # Values with 2mm of spacing around the board
  lpx: px + 2
  lpy: py + 2
  
  # Stagger for all of the different columns
  stagger1: py # ring column one key above the pinky column
  stagger2: 0.3py # middle column .3 key above the ring column
  stagger3: -0.6py # index
  stagger4: -0.2py # inner

  # Sizes of things
  screw_head_diameter: 3.7 # mm
  screw_hole_diameter: 2.2 # mm, close fit for M2
  screw_hole_clearance: 0.5 + 3.7/2 # mm, clearance for screw head from center of hole
  trrs_width: 6.1
  trrs_length: 14.1

  # Other constants
  xiao_shift_x: -1.5
  xiao_shift_y: 1py+0.39

points:
  key:
    spread: 1px
    padding: 1py
  zones:
    matrix:
      columns:
        pinky:
          key:
            column_net: P10
        ring:
          key:
            stagger: stagger1
            column_net: P9
        middle:
          key:
            stagger: stagger2
            column_net: P8
        index:
          key:
            stagger: stagger3
            column_net: P6
        inner:
          key:
            stagger: stagger4
            column_net: P5
      rows:
        bottom:
          row_net: P2
        home:
          row_net: P1
        top:
          row_net: P0
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-2px, -py]
      columns:
        inner:
          key:
            column_net: P8
        middle:
          key:
            column_net: P6
        home:
          key:
            column_net: P5
      rows:
        thumb:
          row_net: P3
  # rotate: -10

outlines:
  board_noround:
    - what: rectangle
      where: true
      size: [lpx, lpy]
    - # Between board and thumbfan
      what: polygon
      points:
        - ref: matrix_middle_bottom
          shift: [0, 0.5lpy]
        - ref: matrix_inner_top
          shift: [0.5lpx, 0.5lpy]
        - ref: thumbfan_home_thumb
          shift: [0.5lpx, 3py + 0.5lpy]
        - ref: thumbfan_home_thumb
          shift: [0.5lpx, -0.5lpy]
        - ref: thumbfan_inner_thumb
          shift: [-0.5lpx, -0.5lpy]
        - ref: matrix_ring_bottom
          shift: [0, -0.5lpy]
        - ref: matrix_ring_home
          shift: [0, 0.5lpy]
    - # MCU
      what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [-12, 29.46]
        - ref: matrix_pinky_top
          shift: [9+lpx, 29.46]
        - ref: matrix_pinky_top
          shift: [0.5lpx, -0.5lpy]
        - ref: matrix_pinky_bottom
          shift: [0.5lpx, -0.5lpy]
        - ref: matrix_pinky_bottom
          shift: [-12, -0.5lpy]
    - # TRRS
      what: polygon
      points:
        - ref: matrix_inner_top # top left
          shift: [-3px, 0.5ky+trrs_width+2*ksx]
        - ref: matrix_inner_top # top right
          shift: [0.5lpx, 0.5ky+trrs_width+2*ksx]
        - ref: matrix_inner_top # bottom right
          shift: [0.5lpx, 0.5ky]
        - ref: matrix_inner_top # bottom left
          shift: [-3px, 0.5ky]

  board:
    - what: outline
      name: board_noround
      fillet: 1

pcbs:
  main:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: pad_diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -0.3py]
      xiao:
        what: xiao
        params:
          orientation: up # Reset button on the bottom
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y]
          rotate: 90
      xiao-reverse:
        what: xiao
        params:
          orientation: down
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y + 2.5]
          rotate: 90
      trrs:
        what: trrs
        where:
          ref: matrix_inner_top
          shift: [8.36, 0.5ky+0.75 + (py-ky)] # 0.75=ref to border
          rotate: -90
        params:
          reverse: true
          symmetric: true
          A: VCC5
          B: VCC5 # A and B overlap
          C: GND
          D: P7
