units:
  # Change "cx" and "cy" to "u" or "U" for MX spacing
  kx: 1.04cx
  ky: 1.04cy
  lkx: kx + 2
  lky: ky + 2
  stagger1: ky
  stagger2: 0.3ky
  stagger3: -0.6ky
  stagger4: -0.2ky
  # distance from XIAO ref to border: 8.89mm
  xiao_shift_x: -1.5
  xiao_shift_y: 1ky+0.39
  trrs_offset_x: -0.5lkx - 5
  trrs_offset_y: 0.5lky + 3.122
  screw_head_diameter: 3.7 # mm
  screw_hole_diameter: 2.2 # mm, close fit for M2
  screw_hole_clearance: 0.5 + 3.7/2 # mm, clearance for screw head from center of hole

points:
  key:
    spread: 1kx
    padding: 1ky
  zones:
    matrix:
      columns:
        pinky:
          key:
            column_net: P10
        ring:
          key:
            stagger: stagger1
            column_net: P9
        middle:
          key:
            stagger: stagger2
            column_net: P8
        index:
          key:
            stagger: stagger3
            column_net: P6
        inner:
          key:
            stagger: stagger4
            column_net: P5
      rows:
        bottom:
          row_net: P2
        home:
          row_net: P1
        top:
          row_net: P0
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-2kx, -ky]
      columns:
        inner:
          key:
            column_net: P8
        middle:
          key:
            column_net: P6
        home:
          key:
            column_net: P5
      rows:
        thumb:
          row_net: P3
  # rotate: -10

outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx, ky]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]

  board_noround:
    - what: rectangle
      where: true
      size: [lkx, lky]
    - # Between board and thumbfan
      what: polygon
      points:
        - ref: matrix_middle_bottom
          shift: [0, 0.5lky]
        - ref: matrix_inner_top
          shift: [0.5lkx, 0.5lky]
        - ref: thumbfan_home_thumb
          shift: [0.5lkx, 3ky + 0.5lky]
        - ref: thumbfan_home_thumb
          shift: [0.5lkx, -0.5lky]
        - ref: thumbfan_inner_thumb
          shift: [-0.5lkx, -0.5lky]
        - ref: matrix_ring_bottom
          shift: [0, -0.5lky]
        - ref: matrix_ring_home
          shift: [0, 0.5lky]
    - # MCU
      what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [-12, 29.46]
        - ref: matrix_pinky_top
          shift: [9+lkx, 29.46]
        - ref: matrix_pinky_top
          shift: [0.5lkx, -0.5lky]
        - ref: matrix_pinky_bottom
          shift: [0.5lkx, -0.5lky]
        - ref: matrix_pinky_bottom
          shift: [-12, -0.5lky]
    - # Bracket support, main board polygon extension
      what: polygon
      points:
        - ref: matrix_middle_top
          shift: [-0.5lkx, -0.5lky]
        - ref: matrix_middle_top
          shift: [0.5lkx, -0.5lky]
        - ref: matrix_middle_top
          shift: [0.5lkx, 0.5lky]
        - ref: matrix_middle_top
          shift: [0.5cx+2*screw_hole_clearance, 0.5lky]
        - ref: matrix_inner_top
          shift: [-4, 0.5lky+6]
        - ref: matrix_inner_top
          shift: [0.5lkx, 0.5lky+6]
        - ref: matrix_inner_top
          shift: [0.5lkx, 0.5lky]

  screw_holes:
    # M2 screw holes
    - what: circle
      where:
        ref: matrix_middle_top
        shift: [0.5cx + screw_hole_clearance, 0.5lky - screw_hole_clearance]
      radius: screw_hole_diameter/2
    - what: circle
      where:
        ref: matrix_index_top
        shift: [-kx + 0.5cx + screw_hole_clearance, 0.5cy + screw_hole_clearance]
      radius: screw_hole_diameter/2
    - what: circle
      where:
        ref: matrix_index_top
        shift: [0.5kx + 5 - screw_hole_clearance, 0.5cy + screw_hole_clearance]
      radius: screw_hole_diameter/2
  board:
    - what: outline
      name: board_noround
      fillet: 1
    - what: outline
      operation: subtract
      name: screw_holes

pcbs:
  main:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: pad_diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -0.3ky]
      xiao:
        what: xiao
        params:
          orientation: up # Reset button on the bottom
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y]
          rotate: 90
      xiao-reverse:
        what: xiao
        params:
          orientation: down
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y + 2.5]
          rotate: 90
      trrs:
        what: trrs
        where:
          ref: matrix_inner_top
          shift: [8.36, 0.5cy+0.75 + (ky-cy)] # 0.75=ref to border
          rotate: -90
        params:
          reverse: true
          symmetric: true
          A: VCC5
          B: VCC5 # A and B overlap
          C: GND
          D: P7

