units:
  # Size of each key. cx and cy for choc, u and U for MX.
  kx: cx
  ky: cy
  # key spread and padding
  px: 1.04kx
  py: 1.04ky
  # From that, get the spacing between keys
  ksx: px-kx
  ksy: py-ky
  lpx: px + 1
  
  # Stagger for all of the different columns
  stagger1: py # ring column one key above the pinky column
  stagger2: 0.3py # middle column .3 key above the ring column
  stagger3: -0.6py # index
  stagger4: -0.2py # inner

  # Other constants
  xiao_shift_x: -1.5
  xiao_shift_y: 1py+0.39

  xiao_ref_to_corner_x: -10.5
  xiao_ref_to_corner_y: 11.39

  left_margin: xiao_shift_x + xiao_ref_to_corner_x
  top_margin: xiao_shift_y + xiao_ref_to_corner_y

points:
  key:
    spread: 1px
    padding: 1py
  zones:
    matrix:
      columns:
        pinky:
          key:
            column_net: P3
        ring:
          key:
            stagger: stagger1
            column_net: P4
        middle:
          key:
            stagger: stagger2
            column_net: P5
        index:
          key:
            stagger: stagger3
            column_net: P6
        inner:
          key:
            stagger: stagger4
            column_net: P8
      rows:
        bottom:
          row_net: P0
        home:
          row_net: P1
        top:
          row_net: P2
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-1px, -py]
      columns:
        inner:
          key:
            column_net: P6
        home:
          key:
            column_net: P8
      rows:
        thumb:
          row_net: P9

outlines:
  board_noround:
    - what: rectangle
      where: true
      size: [lpx, py]
    - # Between board and thumbfan
      what: polygon
      points:
        - ref: matrix_pinky_bottom # Top left
          shift: [-0.5lpx, 1ky]
        - ref: matrix_pinky_bottom # Top right
          shift: [4kx, 1ky]
        - ref: matrix_pinky_bottom # Bottom right
          shift: [4kx, -0.5py]
        - ref: matrix_pinky_bottom # Bottom left
          shift: [-0.5lpx, -0.5py]
    - # MCU
      what: polygon
      points:
        - ref: matrix_pinky_top # Top left
          shift: [left_margin, top_margin]
        - ref: matrix_pinky_top # Top right
          shift: [2px, top_margin]
        - ref: matrix_middle_home # In matrix
        - ref: matrix_ring_home # Same
        - ref: matrix_pinky_home # Same
        - ref: matrix_pinky_bottom # Bottom left
          shift: [0, -0.5py]
        - ref: matrix_pinky_bottom # Bottom left
          shift: [left_margin, -0.5py]

  board:
    - what: outline
      name: board_noround
      fillet: 1

pcbs:
  main:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: pad_diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -0.3py]
      diode_via_1:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [2.8, -0.3py]
      diode_via_2:
        what: via
        where: true
        params:
          net: "{{row_net}}"
        adjust:
          shift: [-2.8, -0.3py]
      key_via_1:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [0, 3.67]
      key_via_2:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [0, 2.67]
      xiao:
        what: xiao
        params:
          orientation: up # Reset button on the bottom
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y + 2.5]
          rotate: 90
      xiao-reverse:
        what: xiao
        params:
          orientation: down
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y]
          rotate: 90
      battery_pad:
        what: battery_pad
        where:
          ref: matrix_middle_bottom
          shift: [5, -0.5ky-2]
          rotate: 0
        params:
          plus: BAT+
          minus: GND
      slider_f:
        what: slider
        where:
          ref: thumbfan_inner_thumb
          shift: [-20, 2]
          rotate: 180
        params:
          from: BAT+
          to: XIAO_BAT+
          side: F
      slider_b:
        what: slider
        where:
          ref: thumbfan_inner_thumb
          shift: [-20, 2]
          rotate: 180
        params:
          from: BAT+
          to: XIAO_BAT+
          side: B
      batt_pad:
        what: pad
        where:
          ref: matrix_pinky_top
          shift: [xiao_shift_x, xiao_shift_y + 2.5]
        params:
          net: XIAO_BAT+
          width: 1.5
          height: 1.5
